import type { SiteTheme } from "@/lib/site/blueprint";
import type { RenderSection } from "@/lib/site/section";

type ExportSite = {
  businessName: string; businessType: string; phone: string | null; email: string | null;
  location: string | null; publicSlug: string; theme: SiteTheme; sections: RenderSection[]; showBranding: boolean;
};

const escape = (value: string) => value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);

export function exportSiteHtml(site: ExportSite, leadEndpoint: string) {
  const phone = site.phone ? `<a href="tel:${escape(site.phone)}">${escape(site.phone)}</a>` : "";
  const whatsapp = site.phone?.replace(/\D/g, "");
  const sections = site.sections.filter((section) => section.isVisible).map((section) => {
    if (section.type === "footer") return `<footer><strong>${escape(section.title || site.businessName)}</strong><p>${escape(section.subtitle)}</p></footer>`;
    if (section.type === "contact") return `<section id="contact"><h2>${escape(section.title || "Contacto")}</h2><p>${escape(section.body)}</p><form id="contact-form"><input name="name" required maxlength="120" placeholder="Nombre"><input name="email" type="email" required maxlength="160" placeholder="Email"><input name="phone" maxlength="40" placeholder="Teléfono"><textarea name="message" required maxlength="2000" placeholder="Mensaje"></textarea><input name="website" class="trap" tabindex="-1" autocomplete="off"><button>${escape(section.ctaText || "Enviar mensaje")}</button><output></output></form></section>`;
    const items = Array.isArray(section.settings.items) ? section.settings.items : [];
    return `<section id="${escape(section.type)}"><p class="eyebrow">${escape(section.subtitle)}</p><h2>${escape(section.title)}</h2><p>${escape(section.body)}</p>${items.length ? `<div class="grid">${items.map((item) => { const record = typeof item === "object" && item ? item as Record<string, unknown> : {}; return `<article><h3>${escape(String(record.title || record.name || ""))}</h3><p>${escape(String(record.description || record.body || record.text || ""))}</p></article>`; }).join("")}</div>` : ""}${section.ctaText ? `<a class="button" href="${escape(section.ctaLink || "#contact")}">${escape(section.ctaText)}</a>` : ""}</section>`;
  }).join("");

  // ponytail: static export intentionally uses one dependency-free HTML file; split assets only when customization requires it.
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(site.businessName)}</title><meta name="description" content="${escape(`${site.businessName} — ${site.businessType}`)}"><style>
:root{--primary:${site.theme.primary};--secondary:${site.theme.secondary};--accent:${site.theme.accent};--bg:${site.theme.background};--text:${site.theme.text}}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.65 system-ui,sans-serif}nav,section,footer{padding:24px max(6vw,24px)}nav{display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;background:var(--bg);border-bottom:1px solid #8883;z-index:2}nav div{display:flex;gap:16px;align-items:center}a{color:inherit}section{max-width:1100px;margin:auto;padding-top:80px;padding-bottom:80px}h1,h2{line-height:1.08}h1{font-size:clamp(2.6rem,8vw,6rem)}h2{font-size:clamp(2rem,5vw,3.8rem)}.hero{min-height:75vh;display:grid;align-content:center}.eyebrow{color:var(--primary);font-weight:700;text-transform:uppercase;letter-spacing:.12em}.button,button{display:inline-block;border:0;border-radius:8px;background:var(--accent);color:#fff;padding:13px 20px;font-weight:700;text-decoration:none;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:20px;margin-top:30px}.grid article,form{padding:24px;border:1px solid #8884;border-radius:12px}form{display:grid;gap:14px;max-width:620px}input,textarea{width:100%;padding:12px;border:1px solid #8886;border-radius:7px;background:transparent;color:inherit;font:inherit}textarea{min-height:130px}.trap{display:none}footer{background:var(--secondary);color:#fff}.whatsapp{position:fixed;right:20px;bottom:20px;background:#25d366;color:#081b0f;border-radius:999px;padding:14px 18px;text-decoration:none;font-weight:700}@media(max-width:640px){nav div{display:none}section{padding-top:56px;padding-bottom:56px}}
</style></head><body><nav><strong>${escape(site.businessName)}</strong><div>${phone}${site.email ? `<a href="mailto:${escape(site.email)}">${escape(site.email)}</a>` : ""}<a href="#contact">Contacto</a></div></nav><section class="hero"><p class="eyebrow">${escape(site.businessType)}</p><h1>${escape(site.businessName)}</h1><p>${escape(site.location || "")}</p><a class="button" href="#contact">Contáctanos</a></section>${sections}${site.showBranding ? '<div style="padding:16px;text-align:center;font-size:13px;color:#888">Creado con Cluster</div>' : ""}${whatsapp && whatsapp.length >= 8 ? `<a class="whatsapp" href="https://wa.me/${whatsapp}" aria-label="Contactar por WhatsApp">WhatsApp</a>` : ""}<script>
const form=document.querySelector('#contact-form');if(form)form.addEventListener('submit',async event=>{event.preventDefault();const output=form.querySelector('output');output.textContent='Enviando…';try{const response=await fetch(${JSON.stringify(leadEndpoint)},{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});if(!response.ok)throw 0;form.reset();output.textContent='Mensaje enviado correctamente.'}catch{output.textContent='No se pudo enviar. Intenta de nuevo.'}});
</script></body></html>`;
}
